### ISSUE TITLE
Update dist files

### ISSUE THREAD

**Issue by bkniffler** [Hacker0x01/react-datepicker#132]
Hi, 
I noticed that the files in /dist folder are not up to date, SSR rendering doesn't work for example. Could you please build those and update to npm? 

Thanks!

**Comment by martijnrusschen** [comment]
I have pushed the latest changes to the dist files. Are they up to date now?

**Comment by bkniffler** [comment]
Hey, thanks.. though I still get server-side:

```
/xxx/node_modules/react-datepicker/node_modules/tether/dist/js/tether.js:406
  var el = document.createElement('div');
           ^
ReferenceError: document is not defined
```

I updated to latest 0.10.0

**Comment by martijnrusschen** [comment]
Looks like the same issue as #137
