### ISSUE TITLE
Crash on clear time input value

### ISSUE THREAD

**Issue by vanekt** [Hacker0x01/react-datepicker#1670]
### Steps to reproduce

1. Pass the "showTimeInput" property to the DatePicker component.
2. Open DatePicker popup
3. Click on the clear button in the time input (or enter invalid value use 'delete' or 'backspace' buttons)

![Screenshot_20190319_144920](https://user-images.githubusercontent.com/10152345/54604371-a6a5ba80-4a57-11e9-8738-060ddccbb75c.png)
![Screenshot_20190319_145010](https://user-images.githubusercontent.com/10152345/54604380-a9a0ab00-4a57-11e9-9bce-ed2d47a0a2ee.png)

**Comment by gautam-relayr** [comment]
Thanks @vanekt for reporting this issue. I will try to fix the issue as soon as possible.

**Comment by martijnrusschen** [comment]
Fixed by #1670

**Comment by De-Santa** [comment]
Issue still occurs. clearing time in input at demo page causes those errors:
![image](https://user-images.githubusercontent.com/16834152/55167767-2ba17a00-51a4-11e9-9fde-ddd693c1d32b.png)

In my case my app crashes with this error
![image](https://user-images.githubusercontent.com/16834152/55167855-4d026600-51a4-11e9-8ba6-24989fa651cf.png)

I`m logging value at onChange method, so after clearing time input dateFns parse result is invalid date

**Comment by gautam-relayr** [comment]
Hi @De-Santa 
It's merged to master but is not released yet. Please wait for the next release to get this fix.

**Comment by glenpadua** [comment]
Is there any workaround to this issue without having to wait for the next release? Have an app in production using this type of time input and running into this issue. Thanks!

**Comment by cpeker** [comment]
Still occurs in IE 11

**Comment by primate-zero** [comment]
If anyone else encounters this issue in React, you can work around it by not calling setState from the onChange callback if the date object passed to the method is invalid.  You can use !isNaN(date.getTime()) to know if the date object is valid.
