### ISSUE TITLE
Render Custom Header example has an error

### ISSUE THREAD

**Issue by lzpat** [Hacker0x01/react-datepicker#1691]
When selecting a month from the month dropdown menu, it results in a NaN error.

```
{months.map(option => (
                    <option key={option} value={option}>
                      {option}
                    </option>
                  ))}
</select>

```
This fixes the error:

```
{months.map((option, i) => (
                              <option key={option} value={i}>
                                {option}
                              </option>
                            ))}

```
https://github.com/Hacker0x01/react-datepicker/blob/master/docs-site/src/examples/render_custom_header.jsx

**Comment by wilarz89** [comment]
I add this code and it works but now it does not load the month of the actual date. 
Did this happen to you?

**Comment by mjangir** [comment]
Fixed the custom header issue in this PR:

https://github.com/Hacker0x01/react-datepicker/pull/1856

Waiting for it to be merged.

**Comment by martijnrusschen** [comment]
Fixed by #1856

**Comment by iloveip** [comment]
I still have a problem. I just copy/ pasted the code from the example, but the app crashed when I open the datepicker. And it shows an error:

```
TypeError: Object(...) is not a function
...
value={months[getMonth(date)]}
```
