### ISSUE TITLE
Undefined class added to custom inputs

### ISSUE THREAD

**Issue by enagy27** [Hacker0x01/react-datepicker#1897]
**Describe the bug**
When using a custom input without a className prop, there will be a value of `undefined` inserted. If the className is defined but empty, the classList will be prepended with an empty space.

**To Reproduce**
- Use a custom input
- Instantiate the custom input without a classname

Example:

Component definition:
```
export const CustomDateInput = React.forwardRef(
  (props: React.HTMLAttributes<HTMLInputElement>, ref: React.Ref<HTMLInputElement>) => (
    <div className={classNames('datepicker-input', 'input-group')}>
      <span className="input-group-addon">
        <Icon name="calendar-outline" />
      </span>
      <input {...props} ref={ref} />
    </div>
  ),
);
```

Use when instantiating `react-datepicker`:
```
customInput={<CustomDateInput />}
```

**Expected behavior**
className should allow `undefined` and simply use the rest of the classes, without prepending any whitespace.

**Comment by martijnrusschen** [comment]
Should be fixed now

**Comment by kelp404** [comment]
I still have this problem at 2.9.6.
And the npm just provides minify code without source map. https://github.com/Hacker0x01/react-datepicker/issues/1693

<img width="1288" alt="螢幕快照 2019-09-17 下午1 24 05" src="https://user-images.githubusercontent.com/1680868/65013710-b8a4df00-d94e-11e9-8120-dbcdb68709b2.png">

```js
<DatePicker {...field}
  selected={field.value && new Date(field.value)}
  customInput={({value, onClick, onChange}) => (
    <input value={value} onClick={onClick} onChange={onChange}/>
  )}
  onChange={value => setFieldValue(field.name, value.toJSON())}/>
```
```json
{
  "react-datepicker": "2.9.6"
}
```

**Comment by enagy27** [comment]
@kelp404 you're seeing something different, I believe. `customInput` is not a render prop, it takes a rendered element (you should be seeing a console error for that propType). Instead try:
```
const CustomInput = ({value, onClick, onChange}) => (
    <input value={value} onClick={onClick} onChange={onChange}/>
  );

<DatePicker
  {...field}
  selected={field.value && new Date(field.value)}
  customInput={<CustomInput />}
  onChange={value => setFieldValue(field.name, value.toJSON())}
/>
```

**Comment by kelp404** [comment]
Hello @enagy27 
Thank you.
I have replaced this package with https://github.com/gpbl/react-day-picker .
I think there are too many issues of this project.
