### ISSUE TITLE
Year dropdown is not working

### ISSUE THREAD

**Issue by EricBrovko** [Hacker0x01/react-datepicker#1953]
**Describe the bug**
The Year dropdown is not working (the datepicker doesn't provide an options of the year) and users can't select a year

**To Reproduce**
1. Go to the official site https://reactdatepicker.com/#example-year-dropdown
2. Try to select a year
3. User sees the error 

**Expected behavior**

**Screenshots**
<img width="904" alt="Screen Shot 2019-10-29 at 7 18 38 PM" src="https://user-images.githubusercontent.com/13108557/67791926-f5511380-fa80-11e9-962d-013bef5fad2c.png">
<img width="225" alt="Screen Shot 2019-10-29 at 7 19 10 PM" src="https://user-images.githubusercontent.com/13108557/67791965-06018980-fa81-11e9-901e-9ef250422f7e.png">

**Additional context**
Example of usage is here
```
import React from "react";
import DatePicker, { registerLocale } from "react-datepicker";
import de from "date-fns/locale/de";
import Input from "../../input";
registerLocale("de", de);

const DatePickerView = (props) => (
  <DatePicker
    { ...props }
    locale="de"
    yearDropdownItemNumber={15}
    customInput={<Input />}
    scrollableYearDropdown 
    showYearDropdown 
  />
);
```
**package.json**
```
"react-datepicker": "^2.9.6",
"date-fns": "^2.6.0"
```

**Comment by Kerry-G** [comment]
To add on @EricBrovko issue, the full message on the website is 

> react-dom.production.min.js:4260 Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&args[]=options for the full message or use the non-minified dev environment for full errors and additional helpful warnings

When I try to replicate this on my own project, the page just hangs indefinitely.

It happens on all dropdown AFAIK.

**Comment by oboro36** [comment]
I have the same problem too.

**Comment by quantumwebco** [comment]
+1

**Comment by Hugo-Meiring** [comment]
I downgraded to version 1.8.0 and things are fine again. But of course, if you need features of 2.x.x this will not work.

**Comment by qenibas** [comment]
Also got the problem.

**Comment by hermance** [comment]
+1
we can't downgrade on our app, is ther a solution other than this?

**Comment by martijnrusschen** [comment]
This should be fixed with #2132 merged. We will release a new version shortly.

**Comment by JSiscar** [comment]
Have just updated react-datepicker in my project and still see this issue.

**Comment by thurrell-atixlabs** [comment]
This should be reopened, the issue is still happening in version 3.6.0

**Comment by rbalukja15** [comment]
Is there any possibility that the issue might be reopened?

**Comment by binomialstew** [comment]
I'm still seeing `Warning: findDOMNode is deprecated in StrictMode` using 3.8.0

**Comment by claradhaleine** [comment]
Chiming in to say, this issue is happening to me too. I’m using 4.1.1.

**Comment by michaelcais** [comment]
Installed 4.7.0 and still sees the warning about findDOMNode is deprecated for both month and year dropdown.

**Comment by bonniesimon** [comment]
I've seen the same issue for month and year dropdown

**Comment by rrja** [comment]
Same here

**Comment by javlund** [comment]
Also here - it seems to work, but I get the error message in the console.

**Comment by linusgsanz** [comment]
We're experiencing the same problem on our side but for iOS Safari.

**Comment by nassihmahmoud** [comment]
I have the same problem, I changed the DATEPICKER version but it doesn't work

![image](https://github.com/Hacker0x01/react-datepicker/assets/7226382/f8e66ab2-3989-4a15-b840-636afd02686d)

**Comment by nassihmahmoud** [comment]
Hello,

Can you help me find a solution

**Comment by hypo-thesis** [comment]
This goes on.

**Comment by yuki0410-dev** [comment]
Is this problem still occurring today?
The sample seemed to work fine in the current version (v6.5.0).
https://reactdatepicker.com/#example-year-dropdown

**Comment by yuki0410-dev** [comment]
( cc. @martijnrusschen )
