### ISSUE TITLE
using showmonthyeardropdown crashes the web page

### ISSUE THREAD

**Issue by ElixirMike** [Hacker0x01/react-datepicker#2023]
Just installed the base version and things were working fine.
However, when I added the attribute showMonthYearDropdown, and then clicked on the down arrow for year, the webpage freezes up and the only way to get out is to kill the page.

I tried showYearDropdown and showMonthdrop down separately, and these seem to work fine.
It appears to be with this specific setting.

**Comment by nicekiwi** [comment]
The show month and year dropdowns also crash in the demo page documentation.

**Comment by martijnrusschen** [comment]
This should be fixed with #2132 merged. We will release a new version shortly.

**Comment by ttchuah** [comment]
Just installed version 3.0.0 today and it's still crashing using the `showMonthYearDropdown` option.

**Comment by slavikdenis** [comment]
Same issues. @ttchuah 's suggesion is a working workaround.

**Comment by pedro-lb** [comment]
Still crashing, so this is not fixed.

For now @ttchuah's solution is working.

**Comment by Azarchaniel** [comment]
Workaround with minMaxDate is working, however if I put min date to 1900-1-1, the result is enormously long select. There should be scrolling.
