### ISSUE TITLE
Custom Input in Typescript showing type error

### ISSUE THREAD

**Issue by AthulNair** [Hacker0x01/react-datepicker#2165]
![image](https://user-images.githubusercontent.com/14287647/83334583-2880ad00-a2c5-11ea-9e8f-6395b2960963.png)

I am trying to implement the customInput functionality and my element looks like this.
```
const CustomDatePickerInput = ({ value, onClick }) => (
  <Badge onClick={onClick} className="display-6 badge  badge-pill float-right p-2 text-white bg-danger" pill>
    {value}
  </Badge>
);
```

I am using this in my typescript project, Some one please help me to solve the type error.

**Comment by flakronkadriu** [comment]
Try updating the @types/react-datepicker or add the badge directly to the customInput prop

**Comment by lamhungypl** [comment]
```javascript
interface Props extends Omit<ReactDatePickerProps, 'onChange'> {
  onClick?(): void;
  onChange?(): void;
}

const Custom = ({ value, onClick, ...rest }) => {
  return <StyledInput value={value} onClick={onClick} {...rest} />;
};
const DatePicker = ({ onClick, onChange, ...rest }: Props) => {
  const [startDate, setStartDate] = React.useState<Date | null>();

  return (
    <ReactDatePicker
      selected={startDate}
      onChange={date => setStartDate(date)}
      placeholderText="dd-mm-yyyy"
      dateFormat="dd-MM-yyyy"
      customInput={
        <Custom value={startDate} onClick={onClick} onChange={onChange} />
      }
      calendarClassName="calendar"
      {...rest}
    />
  );
};
````
I am using this, it works under normal circumstances, not tested much.

**Comment by Coldwine** [comment]
> ```js
> interface Props extends Omit<ReactDatePickerProps, 'onChange'> {
>   onClick?(): void;
>   onChange?(): void;
> }
> 
> const Custom = ({ value, onClick, ...rest }) => {
>   return <StyledInput value={value} onClick={onClick} {...rest} />;
> };
> const DatePicker = ({ onClick, onChange, ...rest }: Props) => {
>   const [startDate, setStartDate] = React.useState<Date | null>();
> 
>   return (
>     <ReactDatePicker
>       selected={startDate}
>       onChange={date => setStartDate(date)}
>       placeholderText="dd-mm-yyyy"
>       dateFormat="dd-MM-yyyy"
>       customInput={
>         <Custom value={startDate} onClick={onClick} onChange={onChange} />
>       }
>       calendarClassName="calendar"
>       {...rest}
>     />
>   );
> };
> ```
> 
> I am using this, it works under normal circumstances, not tested much.

`onClick` and `onChange` should be the internal callbacks that come from `ReactDatePicker` itself, no? In your solution, it looks like you're only trying to satisfy the Typescript compiler with non-existant callbacks.

Is there a chance anyone has a solution to this?

**Comment by oddsson** [comment]
```javascript
import { ReactDatePickerProps} from 'react-datepicker'

interface Props extends ReactDatePickerProps {
  // whatever props you want
}

const Custom = ({ value, onClick}) => {
  return <StyledInput value={value} onClick={onClick} />;
};

const DatePicker = ({ onClick, onChange, ...rest }: Props) => {
  const [startDate, setStartDate] = React.useState<Date | null>();

  return (
    <ReactDatePicker
      customInput={
        <Custom value={startDate} value={value} onClick={onClick}  />
      }
    />
  );
};
```

Initial though is that this works.

**Comment by mantysalo** [comment]
```typescript
const ExampleCustomInput = ({ value, onClick }: {value: string; onClick: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void}) => (
  <button className="example-custom-input" onClick={onClick}>
    {value}
  </button>
);

const ExampleDatePicker = () => <DatePicker customInput={React.createElement(ExampleCustomInput)}/>
```

This seems to work.

**Comment by arxeiss** [comment]
@mantysalo no problem with Typescript, but I got problem with `refs` in the browser console

`Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

**Comment by EmanuelU** [comment]
For a button I had to do this. Not sure if there is a clearner way.

`const CustomInput = (props: React.DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, ref: React.Ref<HTMLButtonElement>) `

**Comment by ShivamJoker** [comment]
It's not stale and it should be fixed

**Comment by dannyjmac** [comment]
Not fixed, still requires attention.

**Comment by flaviobvds** [comment]
Still an issue.
@arxeiss solution solved the problem for me though.

**Comment by AMachulskiy** [comment]
Work this:

`type ButtonProps = React.HTMLProps<HTMLButtonElement>
  const CustomInput = forwardRef<HTMLButtonElement, ButtonProps>(function CustomInput({ value, onClick } , ref) {
    return (
      <button className={styles['custom-input']} onClick={onClick} ref={ref}>
        {value}
      </button>  
    )
  })`
