### ISSUE TITLE
Bad markdown formatting in documentation (datepicker props table)

### ISSUE THREAD

**Issue by tohjustin** [Hacker0x01/react-datepicker#915]
Pipe character for the `union` & `enum` types requires escaping.

https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md

<img width="931" alt="bad markdown formatting" src="https://user-images.githubusercontent.com/8844886/27657203-b473dc92-5c00-11e7-9fca-1f37ab4b3a36.png">

**Comment by rafeememon** [comment]
Fixed in https://github.com/Hacker0x01/react-datepicker/pull/902

**Comment by tohjustin** [comment]
My bad, `master` branch is still showing the old docs though =/
