### ISSUE TITLE
Datepicker demo not working on Github

### ISSUE THREAD

**Issue by martijnrusschen** [Hacker0x01/react-datepicker#94]
The demo (mentioned in the readme) isn't working anymore since the latest PR's has been merged. We should update the dependencies to be fetched from external domains.

**Comment by jonrh** [comment]
+1, came for demo but not working

**Comment by vegetableman** [comment]
same issue

**Comment by RSO** [comment]
@martijnrusschen I pushed a fix, can you get the demo back up and running? I have no clue how any of this works :P

**Comment by martijnrusschen** [comment]
The demo was cached and should work again now. (otherwise do a hard refresh of that page) @jonrh @vegetableman Can you confirm this is working for you now?

**Comment by vegetableman** [comment]
![screen shot 2015-04-08 at 1 26 18 pm](https://cloud.githubusercontent.com/assets/1330851/7040935/f6556b9c-ddf1-11e4-9fb8-5b7669011df1.png)
@martijnrusschen  Did a hard refresh, still the same result for the above url (http://cdn.rawgit.com/Hacker0x01/react-datepicker/master/example/index.html) , although, the demo works fine locally.

**Comment by martijnrusschen** [comment]
Hmm, looks like the old demo is still cached on your side. The new example only uses the `example.js` as source.

**Comment by RSO** [comment]
We should just move to github pages.. Any word on that @martijnrusschen ?

**Comment by martijnrusschen** [comment]
Will work on that soon!
